export const beritaKategori = [
  "Pemerintahan",
  "Pembangunan",
  "Pendidikan",
  "Kesehatan",
  "Lingkungan",
  "Ekonomi dan UMKM",
  "Kebudayaan",
  "Keamanan dan Ketertiban",
  "Sosial Masyarakat",
  "Pariwisata",
  "Olahraga",
  "Agama",
  "Infrastruktur",
  "Teknologi dan Inovasi",
  "Umum",
];
